/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      "light",
      "dark",
      "luxury",
      "dracula",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "black",
      "business",
      "night",
      "coffee",
      "aqua",
      // "cupcake",
      // "bumblebee",
      // "emerald",
      // "corporate",
      // "synthwave",
      // "lofi",
      // "pastel",
      // "fantasy",
      // "wireframe",
      // "cmyk",
      // "autumn",
      // "acid",
      // "lemonade",
      // "winter",
    ],
    base: true,
    styled: true,
    utils: true,
  },
};
